### ISSUE TITLE
NGNIX serving static files

### ISSUE THREAD

**Issue by MikeBinstock** [gchan/dockerfiles#1]
Just wondering if you are considering to use NGINX to server static assets, and o some cache for Ghost.

**Comment by gchan** [comment]
Hi there, thanks for your interest!

I briefly looked at Nginx configuration options for caching static assets but decided to use a CDN (I'm using the free tier of Cloudflare for my blog).

I am open to any Nginx caching suggestions that are simple and easy to maintain. The configuration should also not have any side effects or have a negative effect or experience on Ghost.

Keen to hear your thoughts.
